<?php

namespace Acme\Bundle\IotBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DataPointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataPointRepository extends EntityRepository
{
}
