acme_webchat_homepage:
    path: /
    defaults:
        _controller: AcmeWechatBundle:Default:index

acme_wechat_signature:
    path: /api/checksignature
    defaults:
        _controller: AcmeWechatBundle:Wechat:checksignature

acme_wechat_access_token:
    path: /api/access_token
    defaults:
        _controller: AcmeWechatBundle:Wechat:getAccessToken