<?php

namespace Acme\Bundle\AlertBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlertRuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertRuleRepository extends EntityRepository
{
  public function findOneBySnJoinedToUser($deviceSn, $userName)
  {
      $query = $this->getEntityManager()
                    ->createQuery(
                          'SELECT a FROM AcmeAlertBundle:AlertRule a
                           JOIN a.user u
                           JOIN a.device d
                           WHERE d.sn = :sn AND u.username = :username
                          '
                      )
                    ->setParameter('sn', $deviceSn)
                    ->setParameter('username', $userName);
      try {
          return $query->getSingleResult();
      } catch (\Doctrine\ORM\NoResultException $e) {
          return null;
      }
  }

  public function findOneBySnJoinedToDevice($deviceSn)
    {
        $query = $this->getEntityManager()
                      ->createQuery(
                            'SELECT a FROM AcmeAlertBundle:AlertRule a
                             JOIN a.device d
                             WHERE d.sn = :sn
                            '
                        )
                      ->setParameter('sn', $deviceSn);
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }    

    public function SearchSnAlertRuleDescById($deviceSn)
    {
        $query = $this->getEntityManager()
                      ->createQuery(
                            'SELECT a FROM AcmeAlertBundle:AlertRule a
                             JOIN a.device d
                             WHERE d.sn = :sn ORDER BY a.id DESC limit 1
                            '
                        )
                      ->setParameter('sn', $deviceSn);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
