acme_web:
    resource: "@AcmeWebBundle/Resources/config/routing/web.yml"
    prefix:   /web

qomo_backend:
    resource: "@AcmeWebBundle/Resources/config/routing/backend/main.yml"
    prefix: /administration

acme_iot:
    resource: "@AcmeIotBundle/Resources/config/routing/main.yml"
    prefix:   /iot

acme_iot_api:
    resource: "@AcmeIotBundle/Resources/config/routing/apiv1_1.yml"
    prefix:   /iotdev/v1.1

acme_wechat:
    resource: "@AcmeWechatBundle/Resources/config/routing/main.yml"
    prefix:   /wechat

acme_iot_user:
    resource: "@AcmeUserBundle/Resources/config/routing/main.yml"
    prefix:   /user

acme_alert:
    resource: "@AcmeAlertBundle/Resources/config/routing/main.yml"
    prefix:   /alert

acme_fedex:
    resource: "@AcmeFedexBundle/Resources/config/routing/main.yml"
    prefix:   /fedex

acme_frontend:
    resource: "@AcmeWebBundle/Resources/config/routing/frontend/main.yml"
    prefix:   /front

