<?php

namespace Acme\Bundle\FedexBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AcquireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcquireRepository extends EntityRepository
{
}
